/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            version?: string;
                        };
                    };
                };
                default: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the watchlist */
        get: operations["listProducts"];
        put?: never;
        /** Track a product */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a product */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /** Stop tracking (history is purged asynchronously) */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /** Update name, target, frequency or paused state */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/v1/products/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Price history */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Recent checks, newest first */
        get: operations["listChecks"];
        put?: never;
        /** Queue a manual check (5-minute cooldown per product) */
        post: operations["triggerCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}/checks/{checkId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                checkId: string;
            };
            cookie?: never;
        };
        /** Check status */
        get: operations["getCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update notification settings */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/retailers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supported retailers */
        get: operations["listRetailers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Money: {
            /** @example 94.00 */
            amount: string;
            /** @example USD */
            currency: string;
        };
        CreateProductRequest: {
            name: string;
            url: string;
            target_price: components["schemas"]["Money"];
            /**
             * @default 6h
             * @enum {string}
             */
            check_frequency: "1h" | "6h" | "12h" | "24h";
        };
        UpdateProductRequest: {
            name?: string;
            target_price?: components["schemas"]["Money"];
            /** @enum {string} */
            check_frequency?: "1h" | "6h" | "12h" | "24h";
            paused?: boolean;
        };
        Product: {
            id: string;
            name: string;
            url: string;
            /** @description Retailer profile ID, or "generic" */
            retailer: string;
            target_price: components["schemas"]["Money"];
            current_price: components["schemas"]["Money"] | null;
            lowest_price: components["schemas"]["Money"] | null;
            /** @enum {string} */
            availability: "IN_STOCK" | "OUT_OF_STOCK" | "UNKNOWN";
            /** @enum {string} */
            check_frequency: "1h" | "6h" | "12h" | "24h";
            /** @enum {string} */
            status: "ACTIVE" | "PAUSED" | "NEEDS_ATTENTION" | "GONE";
            /** @description Last successful price is older than 3 check intervals */
            stale: boolean;
            alert: {
                /** @enum {string} */
                state: "ARMED" | "TRIGGERED";
                /** Format: date-time */
                triggered_at: string | null;
            };
            /** Format: date-time */
            last_checked_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            /** Format: date-time */
            next_check_at: string | null;
            last_error: {
                code: components["schemas"]["OutcomeCode"];
                retryable: boolean;
            } | null;
            latest_check?: {
                id: string;
                status: components["schemas"]["CheckStatus"];
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Increments on user edits; also exposed as the ETag */
            version: number;
        };
        PriceHistory: {
            product_id: string;
            currency: string;
            /** @enum {string} */
            resolution: "raw" | "downsampled";
            points: {
                /** Format: date-time */
                t: string;
                price: string;
                /** @enum {string} */
                availability: "IN_STOCK" | "OUT_OF_STOCK" | "UNKNOWN";
                /** @description Anomalous value awaiting confirmation; never triggers alerts */
                suspect?: boolean;
            }[];
            summary: {
                min: string | null;
                max: string | null;
                latest: string | null;
                count: number;
            };
            next_cursor?: string;
        };
        /** @enum {string} */
        CheckStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "SKIPPED";
        /** @enum {string} */
        OutcomeCode: "OK" | "PRICE_NOT_FOUND" | "AMBIGUOUS_PRICE" | "IMPLAUSIBLE_PRICE" | "CURRENCY_MISMATCH" | "FETCH_TRANSIENT" | "RATE_LIMITED" | "BLOCKED" | "ROBOTS_DISALLOWED" | "NOT_FOUND" | "FORBIDDEN_TARGET" | "UNSUPPORTED_CONTENT" | "TOO_LARGE" | "HTTP_ERROR" | "CIRCUIT_OPEN" | "PRODUCT_INACTIVE";
        Check: {
            check_id: string;
            product_id: string;
            status: components["schemas"]["CheckStatus"];
            /** @enum {string} */
            trigger: "INITIAL" | "SCHEDULED" | "MANUAL" | "RECHECK";
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            duration_ms: number | null;
            result: {
                price: components["schemas"]["Money"] | null;
                /** @enum {string} */
                strategy?: "jsonld" | "meta" | "selectors";
                alert_triggered: boolean;
            } | null;
            error: {
                code: components["schemas"]["OutcomeCode"];
                message?: string;
                retryable: boolean;
            } | null;
            links: {
                [key: string]: string;
            };
        };
        Profile: {
            user_id: string;
            email: string;
            notifications_enabled: boolean;
            product_count: number;
            product_limit: number;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            request_id?: string;
            existing_product_id?: string;
            errors?: {
                field: string;
                code: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Product"][];
                        next_cursor?: string;
                    };
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Ninja Air Fryer",
                 *       "url": "https://shop.example.com/p/ninja-af101?utm_source=newsletter",
                 *       "target_price": {
                 *         "amount": "100.00",
                 *         "currency": "USD"
                 *       },
                 *       "check_frequency": "6h"
                 *     }
                 */
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Created; the first check is queued. */
            201: {
                headers: {
                    Location?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag from a previous response; returns 412 if the product changed. */
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "target_price": {
                 *         "amount": "90.00",
                 *         "currency": "USD"
                 *       },
                 *       "check_frequency": "12h"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getPrices: {
        parameters: {
            query?: {
                /** @description RFC 3339; default 30 days before `to` */
                from?: string;
                /** @description RFC 3339; default now */
                to?: string;
                /** @description Downsample the whole range for charting (min/max per bucket) */
                max_points?: number;
                /** @description Raw page size (ignored with max_points) */
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistory"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listChecks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Check"][];
                    };
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    triggerCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"];
                };
            };
            404: components["responses"]["Problem"];
            /** @description Cooldown in effect */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                checkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Check"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    notifications_enabled: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listRetailers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Whether sites without a profile are accepted (structured data only) */
                        generic_allowed: boolean;
                        items: {
                            id: string;
                            name: string;
                            domains: string[];
                            currency?: string;
                        }[];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
